services:
  # Backend API
  - type: web
    name: twinflow-backend
    runtime: docker
    repo: https://github.com/prajwal-Inovator/Traffic_twinflow-ai
    branch: main
    plan: starter
    dockerfilePath: docker/Dockerfile.backend
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: CORS_ORIGINS
        value: https://twinflow-frontend.onrender.com

      # Fill these in Render Dashboard
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENAQ_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false

      - key: DEBUG
        value: "false"

  # AI Service
  - type: web
    name: twinflow-ai
    runtime: docker
    repo: https://github.com/prajwal-Inovator/Traffic_twinflow-ai
    branch: main
    plan: starter
    dockerfilePath: docker/Dockerfile.ai
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DEBUG
        value: "false"

  # SUMO Worker
  - type: worker
    name: twinflow-simulation
    runtime: docker
    repo: https://github.com/prajwal-Inovator/Traffic_twinflow-ai
    branch: main
    plan: starter
    dockerfilePath: docker/Dockerfile.simulation
    dockerContext: .
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DEBUG
        value: "false"

    # Frontend
  - type: web
    runtime: static
    name: twinflow-frontend
    repo: https://github.com/prajwal-Inovator/Traffic_twinflow-ai
    branch: main
    rootDir: frontend
    buildCommand: npm ci
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://twinflow-backend.onrender.com
      - key: VITE_WS_URL
        value: wss://twinflow-backend.onrender.com/ws
      - key: VITE_MAPBOX_TOKEN
        sync: false
