# Base image
FROM ubuntu:22.04

# Avoid prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    sumo \
    sumo-tools \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

COPY simulation/ /app/

# Generate valid SUMO network
RUN netconvert --node-files=/app/network.nod.xml --edge-files=/app/network.edg.xml --output-file=/app/network.net.xml

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 10000

CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]